### ISSUE TITLE
missing "OS", "OS.time", "OS.unit", "RFS", "RFS.time", "RFS.unit" columns in the downloaded clinical infomration file from TCGA

### ISSUE THREAD

**Issue by danshu** [ropensci/UCSCXenaTools#22]
Hello,

I'm following this tutorial "TCGA Pan-cancer data download" (https://xsliulab.github.io/tumor-immunogenicity-score/#data-download-and-preprocessing) to download and clean TCGA clinical data.
However, columns like "OS", "OS.time", "OS.unit", "RFS", "RFS.time", "RFS.unit" are expected to be but absent in the clinical information files. 
Is this due to updates of the "UCSCXenaTools" package?

Best,
Danshu

**Comment by ShixiangWang** [comment]
@danshu Thanks for reporting. I checked and found this is due to the updates of UCSC Xena for Clinical data.  The recent version is 2019-12-06, you can view [this LUAD cohort](https://xenabrowser.net/datapages/?dataset=TCGA.LUAD.sampleMap%2FLUAD_clinicalMatrix&host=https%3A%2F%2Ftcga.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443). I did not find any version control, so we can't download older version data now. You have to do some dirty clean data for yourself,  or you can use the tidy data from <https://github.com/XSLiuLab/tumor-immunogenicity-score/blob/master/report/results/TCGA_tidy_Clinical.RData>.

Hope it help.

Best,
Shixiang

**Comment by danshu** [comment]
@ShixiangWang Thanks!
