### ISSUE TITLE
Error downloading CCLE datasets from publicHub

### ISSUE THREAD

**Issue by vuzun** [ropensci/UCSCXenaTools#25]
Hi,

I'm trying to download CCLE files, but I get the file missing message:

` cannot open URL 'https://ucscpublic.xenahubs.net/download/ccle/CCLE_copynumber_2013-12-03.seg.txt': HTTP status was '404 Not Found'`

The code I use:
```
mysets <- XenaGenerate(subset = XenaHostNames=="publicHub") %>%
    XenaFilter(filterCohorts = "CCLE")
XenaQuery(mysets) %>%
    XenaDownload() -> ccle_download
```

If I try the same with MAGIC datasets, it works fine.

**Comment by ShixiangWang** [comment]
@vuzun Thanks for reporting, there are some problems for querying the data. I need to contact with the UCSC Xena team.

I will let you know if it is fixed.

**Comment by ShixiangWang** [comment]
@vuzun Sorry for the late reply, I forgot the response from Xena team. I am sorry to tell you that the CCLE cohort can not be downloaded by UCSCXenaTools due to the permission.

The response is:

> Hi Shixiang,
>
>So great to hear from you! Unfortunately we are not authorized to provide downloads of the CCLE data. CCLE wants users of the data to go through them instead.
>
>Let me know if there's anything else I can help with!
>
>Best,
>Mary

I recommend you downloaded raw datasets from https://data.broadinstitute.org/ccle/ or https://portals.broadinstitute.org/ccle/data (need login)
